[app:main]
use: call:query:create_app

# Elasticsearch configuration. The WebSocket does not actually use ES but
# it does use the same config loading code which checks for these settings.
config: data/config.yaml
bert-base-uncased: data/bert-base-uncased
id_vocab: data/id_vocab.txt
fine_tune_checkpoint_title: data/fine_tune_checkpoint_title_58.pth
all_docid_knowledge: data/all_docid_knowledge.json

[loggers]
keys = root, gunicorn.error, query

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console

[logger_gunicorn.error]
level = INFO
handlers =
qualname = gunicorn.error

[logger_query]
level = INFO
handlers =
qualname = query

[handler_console]
level = NOTSET
class = StreamHandler
args = ()
formatter = generic

[formatter_generic]
format = %(asctime)s [%(process)d] [%(name)s:%(levelname)s] %(message)s
